language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.1
  - 7.2

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

install:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction

script:
  - composer test
